ThomasGreg/ControleCadastro.Front/Models/Endereco.cs
using System.Text.Json.Serialization;

namespace ControleCadastro.Front.Models
{
    public class Endereco
    {
        public int Id { get; set; }
        public string Logadouro { get; set; }
        public string Numero { get; set; }
        public string Cep { get; set; }
        public string Complemento { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public bool IsPrincipal { get; set; }

        public Endereco() { }
    }
}

ThomasGreg/ControleCadastro.Front/Controllers/EnderecoController.cs
namespace ControleCadastro.Front.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Net.Http;
    using System.Text.Json;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using ControleCadastro.Front.Models; 
    using System.Web;

    public class EnderecoController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly string _linkApi;

        public EnderecoController(HttpClient httpClient, IConfiguration configuration)
        {
            var handler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
            };

            _httpClient = new HttpClient(handler);
            _linkApi = configuration["LinkApi"];
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var token = HttpContext.Session.GetString("AuthToken");

                if (string.IsNullOrEmpty(token))
                    return RedirectToAction("Login", "Login");

                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await _httpClient.GetAsync($"{_linkApi}api/Endereco/listarTodos");

                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    var enderecoResponse = JsonSerializer.Deserialize<List<Endereco>>(json);

                    if (enderecoResponse != null && enderecoResponse.Any())
                    {
                        return View(enderecoResponse);
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Nenhum endereço encontrado.";
                        return View(new List<Endereco>());
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Erro ao carregar endereços.";
                    return View(new List<Endereco>());
                }
            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = "Ocorreu um erro inesperado. Tente novamente mais tarde.";
                return View(new List<Endereco>());
            }
        }

        public async Task<IActionResult> Inserir()
        {
            var token = HttpContext.Session.GetString("AuthToken");

            if (string.IsNullOrEmpty(token))
                return RedirectToAction("Login", "Login");


            return View(new Endereco());

        }
        [HttpPost]
        public async Task<IActionResult> Inserir(Endereco endereco, string action)
        {
            try
            {
                var token = HttpContext.Session.GetString("AuthToken");

                if (string.IsNullOrEmpty(token))
                    return RedirectToAction("Login", "Login");

                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var json = JsonSerializer.Serialize(endereco);
                var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync($"{_linkApi}api/Endereco/inserir", content);

                var jsonResponse = await response.Content.ReadAsStringAsync();
                var apiResponse = JsonSerializer.Deserialize<ApiResposta>(jsonResponse);

                if (response.IsSuccessStatusCode)
                {
                    if (apiResponse != null && apiResponse.Codigo == 200)
                    {
                        TempData["Message"] = apiResponse.Mensagem;
                        TempData["Codigo"] = apiResponse.Codigo;
                        return RedirectToAction("Index"); 
                    }
                    else
                    {
                        TempData["Message"] = apiResponse.Mensagem;
                        TempData["Codigo"] = apiResponse.Codigo;
                        return View(endereco);
                    }
                }

                TempData["Message"] = response.ReasonPhrase;
                TempData["Codigo"] = response.StatusCode;
                return View(endereco);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["Codigo"] = 500;
                return View(new Endereco());
            }

        }
        
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var token = HttpContext.Session.GetString("AuthToken");

                if (string.IsNullOrEmpty(token))
                    return RedirectToAction("Login", "Login");

                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await _httpClient.GetAsync($"{_linkApi}api/Endereco/consultarPorId{id}");

                var jsonResponse = await response.Content.ReadAsStringAsync();
                var apiResponse = JsonSerializer.Deserialize<ApiResposta>(jsonResponse);

                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();

                    var enderecoResponse = JsonSerializer.Deserialize<Endereco>(json);

                    if (enderecoResponse == null)
                    {
                        ViewBag.ErrorMessage = "Erro ao carregar o endereço.";
                        return RedirectToAction("Index");
                    }

                    return View(enderecoResponse);
                }

                TempData["Message"] = response.ReasonPhrase;
                TempData["Codigo"] = response.StatusCode;
                return View(new Endereco());
            }
            catch (Exception ex)
            {
                
                ViewBag.ErrorMessage = "Ocorreu um erro inesperado. Tente novamente mais tarde.";
                return View(new Endereco());
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Endereco endereco, string action)
        {
            try
            {
                var token = HttpContext.Session.GetString("AuthToken");

                if (string.IsNullOrEmpty(token))
                    return RedirectToAction("Login", "Login");

                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var json = JsonSerializer.Serialize(endereco);
                var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

                var response = await _httpClient.PutAsync($"{_linkApi}api/Endereco/editar", content);

                var jsonResponse = await response.Content.ReadAsStringAsync();
                var apiResponse = JsonSerializer.Deserialize<ApiResposta>(jsonResponse);

                if (response.IsSuccessStatusCode)
                {

                    if (apiResponse != null && apiResponse.Codigo == 200)
                    {
                        TempData["Message"] = apiResponse.Mensagem;
                        TempData["Codigo"] = apiResponse.Codigo;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Message"] = apiResponse.Mensagem;
                        TempData["Codigo"] = apiResponse.Codigo;
                        return View(endereco);
                    }
                }

                TempData["Message"] = response.ReasonPhrase;
                TempData["Codigo"] = response.StatusCode;
                return View(endereco);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["Codigo"] = 500;
                return View(new Endereco());
            }
        }


        // Ação de Excluir
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var token = HttpContext.Session.GetString("AuthToken");

                if (string.IsNullOrEmpty(token))
                    return RedirectToAction("Login", "Login");

                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await _httpClient.DeleteAsync($"{_linkApi}api/Endereco/{id}");

                var jsonResponse = await response.Content.ReadAsStringAsync();
                var apiResponse = JsonSerializer.Deserialize<ApiResposta>(jsonResponse);

                if (response.IsSuccessStatusCode)
                {
                    if (apiResponse != null && apiResponse.Codigo == 200)
                    {
                        TempData["Message"] = apiResponse.Mensagem;
                        TempData["Codigo"] = apiResponse.Codigo;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Message"] = apiResponse.Mensagem;
                        TempData["Codigo"] = apiResponse.Codigo;
                        return RedirectToAction("Index"); 
                    }
                }

                TempData["Message"] = response.ReasonPhrase;
                TempData["Codigo"] = response.StatusCode;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["Codigo"] = 500;
                return RedirectToAction("Index"); 
            }
            
        }

ThomasGreg/ControleCadastro.Front/Views/Endereco/Edit.cshtml
@model Endereco

@{
    ViewData["Title"] = "Editar Endereço";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success">
        @TempData["Message"]
    </div>
}


<h2>@ViewData["Title"]</h2>

<form asp-action="Edit" method="post">

    <div class="form-group">
        <label for="Logadouro">Logradouro</label>
        <input type="text" class="form-control" id="Logadouro" name="Logadouro" value="@Model.Logadouro" required />
    </div>

    <div class="form-group">
        <label for="Numero">Número</label>
        <input type="text" class="form-control" id="Numero" name="Numero" value="@Model.Numero" required />
    </div>

    <div class="form-group">
        <label for="Cep">CEP</label>
        <input type="text" class="form-control" id="Cep" name="Cep" value="@Model.Cep" required maxlength="10"/>
    </div>

    <div class="form-group">
        <label for="Complemento">Complemento</label>
        <input type="text" class="form-control" id="Complemento" name="Complemento" value="@Model.Complemento" />
    </div>

    <div class="form-group">
        <label for="Cidade">Cidade</label>
        <input type="text" class="form-control" id="Cidade" name="Cidade" value="@Model.Cidade" required />
    </div>

    <div class="form-group">
        <label for="Estado">Estado</label>
        <input type="text" class="form-control" id="Estado" name="Estado" value="@Model.Estado" required />
    </div>

    <div class="form-group">
        <label for="IsPrincipal">Principal</label>
        <select class="form-control" id="IsPrincipal" name="IsPrincipal">
            <option value="true" selected="@(Model.IsPrincipal)">Sim</option>
            <option value="false" selected="@(Model.IsPrincipal)">Não</option>
        </select>
    </div>
    <br>

    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="@Url.Action("Index", "Endereco")" class="btn btn-secondary">Cancelar</a>
</form>

ThomasGreg/ControleCadastro.Front/Views/Endereco/Index.cshtml
@model List<Endereco>

@{
    ViewData["Title"] = "Lista de Endereços";
}

<h2>@ViewData["Title"]</h2>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Logradouro</th>
                <th>Número</th>
                <th>CEP</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Principal</th>
                <th>Ações</th> 
            </tr>
        </thead>
        <tbody>
            @foreach (var endereco in Model)
            {
                <tr>
                    <td>@endereco.Id</td>
                    <td>@endereco.Logadouro</td>
                    <td>@endereco.Numero</td>
                    <td>@endereco.Cep</td>
                    <td>@endereco.Cidade</td>
                    <td>@endereco.Estado</td>
                    <td>@(endereco.IsPrincipal ? "Sim" : "Não")</td>
                    <td>
                        <!-- Botão de Editar -->
                        <a href="@Url.Action("Edit", "Endereco", new { id = endereco.Id })" class="btn btn-primary" style="transform: scale(0.95);">Editar</a>

                        <!-- Botão de Excluir -->
                        <form action="@Url.Action("Delete", "Endereco", new { id = endereco.Id })" method="post" style="display:inline;">
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja excluir este endereço?')" style="transform: scale(0.95);">Excluir</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Nenhum endereço encontrado.</p>
}


<div class="row mt-3">
    <div class="d-flex justify-content-between mt-3">
        <!-- Botão de Atualizar -->
        <a href="@Url.Action("Index", "Endereco")" class="btn btn-warning" style="transform: scale(0.95);">Atualizar Lista</a>

        <!-- Botão de Adicionar -->
        <a href="@Url.Action("Inserir", "Endereco")" class="btn btn-success" style="transform: scale(0.95);">Adicionar</a>
    </div>
</div>

ThomasGreg/ControleCadastro.Front/Views/Endereco/Inserir.cshtml
@model Endereco

@{
    ViewData["Title"] = "Inserir Endereço";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success">
        @TempData["Message"]
    </div>
}


<h2>@ViewData["Title"]</h2>

<form asp-action="Inserir" method="post">
    <input type="hidden" id="EnderecoId" name="Id" value="@Model.Id" />

    <div class="form-group">
        <label for="Logadouro">Logradouro</label>
        <input type="text" class="form-control" id="Logadouro" name="Logadouro" value="@Model.Logadouro" required />
    </div>

    <div class="form-group">
        <label for="Numero">Número</label>
        <input type="text" class="form-control" id="Numero" name="Numero" value="@Model.Numero" required />
    </div>

    <div class="form-group">
        <label for="Cep">CEP</label>
        <input type="text" class="form-control" id="Cep" name="Cep" value="@Model.Cep" required maxlength="10"/>
    </div>

    <div class="form-group">
        <label for="Complemento">Complemento</label>
        <input type="text" class="form-control" id="Complemento" name="Complemento" value="@Model.Complemento" />
    </div>

    <div class="form-group">
        <label for="Cidade">Cidade</label>
        <input type="text" class="form-control" id="Cidade" name="Cidade" value="@Model.Cidade" required />
    </div>

    <div class="form-group">
        <label for="Estado">Estado</label>
        <input type="text" class="form-control" id="Estado" name="Estado" value="@Model.Estado" required />
    </div>

    <div class="form-group">
        <label for="IsPrincipal">Principal</label>
        <select class="form-control" id="IsPrincipal" name="IsPrincipal">
            <option value="true" selected="@(Model.IsPrincipal)">Sim</option>
            <option value="false" selected="@(Model.IsPrincipal)">Não</option>
        </select>
    </div>
    <br>

    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="@Url.Action("Index", "Endereco")" class="btn btn-secondary">Cancelar</a>
</form>